ANIME_DATABASE = {
    "naruto": {
        "title": "Naruto / Naruto Shippuden",
        "themes": ["Willpower", "Friendship", "Redemption", "War"],
        "power_system": "Chakra-based ninjutsu",
        "political_structure": "Hidden Village Military System",
        "tone": "Shonen Action",
    },
    "attack_on_titan": {
        "title": "Attack on Titan",
        "themes": ["Freedom", "Oppression", "War", "Cycle of Hatred"],
        "power_system": "Titan Shifting",
        "political_structure": "Military Oligarchy",
        "tone": "Dark Political Thriller",
    },
    "death_note": {
        "title": "Death Note",
        "themes": ["Justice", "Morality", "God Complex", "Control"],
        "power_system": "Supernatural Death Notebook",
        "political_structure": "Modern Society + Shadow Governance",
        "tone": "Psychological Thriller",
    },
    "one_piece": {
        "title": "One Piece",
        "themes": ["Freedom", "Adventure", "Dreams", "Revolution"],
        "power_system": "Devil Fruits + Haki",
        "political_structure": "World Government + Pirate Era",
        "tone": "Epic Adventure",
    },
    "fullmetal_alchemist": {
        "title": "Fullmetal Alchemist: Brotherhood",
        "themes": ["Equivalent Exchange", "Sacrifice", "Truth", "War"],
        "power_system": "Alchemy",
        "political_structure": "Military State",
        "tone": "Philosophical Action",
    },
    "hunter_x_hunter": {
        "title": "Hunter x Hunter (2011)",
        "themes": ["Ambition", "Morality", "Human Nature"],
        "power_system": "Nen",
        "political_structure": "Hunter Association + Independent Nations",
        "tone": "Dark Shonen",
    },
    "cowboy_bebop": {
        "title": "Cowboy Bebop",
        "themes": ["Loneliness", "Past Regret", "Existentialism"],
        "power_system": "None (Realistic Combat)",
        "political_structure": "Interplanetary Society",
        "tone": "Space Western",
    },
    "dragon_ball_z": {
        "title": "Dragon Ball Z",
        "themes": ["Strength", "Growth", "Protection"],
        "power_system": "Ki Energy",
        "political_structure": "Loose Galactic Structure",
        "tone": "High Power Action",
    },
    "neon_genesis_evangelion": {
        "title": "Neon Genesis Evangelion",
        "themes": ["Depression", "Identity", "Existentialism"],
        "power_system": "Biomechanical Mecha",
        "political_structure": "Secret Organization (NERV)",
        "tone": "Psychological Mecha",
    },
    "berserk": {
        "title": "Berserk (1997)",
        "themes": ["Fate", "Struggle", "Ambition", "Betrayal"],
        "power_system": "Dark Supernatural",
        "political_structure": "Feudal Kingdoms",
        "tone": "Dark Fantasy",
    },
}
